apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: astrolabe
resources:
- bases/astrolabe.io_stacks.yaml
- bases/astrolabe.io_modules.yaml
