---
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds-dev
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: my-access-key
  AWS_SECRET_ACCESS_KEY: my-secret-key
  AWS_DEFAULT_REGION: us-east-1
  AWS_REGION: us-east-1
---
apiVersion: astrolabe.io/v1
kind: Stack
metadata:
  name: aws-vpc-demo
spec:
  backendRef:
    name: aws-s3-backend
  credentialRef:
    name: aws-creds-dev
  modules:
    - name: aws-vpc-git
      variables:
        name: "demo-vpc"
        cidr: "10.0.0.0/16"
        azs: ["us-west-2a", "us-west-2b"]
        private_subnets: ["10.0.1.0/24", "10.0.2.0/24"]
        public_subnets: ["10.0.101.0/24", "10.0.102.0/24"]
        enable_dns_hostnames: true
        enable_dns_support: true
        tags:
          Environment: "demo"
          Owner: "infra-team"
      dependsOn: []
---
