---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - astrolabe.io
  resources:
  - backendconfigs
  - credentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - astrolabe.io
  resources:
  - modules
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - astrolabe.io
  resources:
  - modules/status
  - stacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - astrolabe.io
  resources:
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - astrolabe.io
  resources:
  - stacks/finalizers
  verbs:
  - update
