apiVersion: astrolabe.io/v1
kind: BackendConfig
metadata:
  name: aws-s3-backend
spec:
  type: s3
  settings:
    bucket: my-tf-state-bucket
    region: us-west-2
  credentialRef:
    name: my-backend-credentials
