---
apiVersion: astrolabe.io/v1
kind: Stack
metadata:
  name: random-hello
spec:
  backendConfig:
    type: local
    settings:
      path: "terraform.tfstate"
  modules:
    - name: hello
      variables:
        some_key: "astrolabe"
        hellos:
          hello: "Hello, Astrolabe!"
          second_hello: "Hi from Juned!"
---
apiVersion: astrolabe.io/v1
kind: Module
metadata:
  name: hello
spec:
  source:
    type: git
    url: "https://github.com/joatmon08/terraform-random-hello.git"
    version: "v6.0.0"
---
